### PR TITLE
Add PHP7.1 to test suite & fix compatibility.

### PR DESCRIPTION
**Pull request by markstory**
Refs #106

### CODE REVIEW

**Comment by lorenzo** [comment]
Is it expected for the build to fail?

**Comment by dereuromark** [comment]
No, looks like there are more hidden bombs in the minor version jump regarding BC breaking.

**Comment by markstory** [comment]
@lorenzo No I hoped it would pass with the 1 known problem fixed. But we didn't get lucky.

**Comment by markstory** [comment]
I think I've gotten the tests fixed. I had to remove some tests as the addition of microtime in PHP7.1 has caused tests to no longer pass in some scenarios.

**Comment by lorenzo** [comment]
Good job!

**Comment by systematical84** [comment]
Has a fix for this been released on the 3.3 branch yet?

**Comment by markstory** [comment]
Yes. You will need to use composer to update to the latest version of chronos

**Comment by bravo-kernel** [comment]
✅

**Pull request merged**
