### PR TITLE
Extract more traits

### PR DESCRIPTION
**Pull request by markstory**
I've split out 3 more traits, and cleaned up the interface a bit.

I felt that having static methods in the interface was of little/no value, but I'm happy to put them back if others disagree.

Refs #12

### CODE REVIEW

**Comment by antograssiot** [comment]
I've removed some extra use statements. I can re-add them if you think it increase dependencies readability.

**Comment by dereuromark** [comment]
Only one remark: All traits are singular "Timezone", "Comparison", etc.
I think the "Modifiers" trait should be named "Modifier" Trait as well.

**Comment by markstory** [comment]
@dereuromark Good point. I will fix that up.

**Comment by jadb** [comment]
Nice catch @dereuromark!

**Pull request merged**
