### PR TITLE
Fix: addWeekday(s) clears time

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/chronos/issues/54

what about subWeekday and subWeekdays?
Those havent been fixed in carbon yet, but IMO should also be fixed.

### CODE REVIEW

**Comment by dereuromark** [comment]
I now also fixed up the sub methods. But it seems there is some other bug occurring now: 
```
1) Cake\Chronos\Test\DateTime\SubTest::testSubWeekdaysPositive with data set "mutable" ('Cake\Chronos\MutableDateTime')
Exception: DateTimeZone::__construct(): Unknown or bad timezone (13)
```

**Comment by markstory** [comment]
Code looks good. Do the tests also fail for you locally?

**Comment by dereuromark** [comment]
Yes. Could this be a PHP bug with going back over the 1.1.?

**Comment by dereuromark** [comment]
So the CS error is a regression in their sniffer: https://github.com/squizlabs/PHP_CodeSniffer/issues/786
Looks like this is OK to be merged then.

**Pull request merged**
