### PR TITLE
Implement setTimeFromTimeString()

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/chronos/issues/49

### CODE REVIEW

**Comment by lorenzo** [comment]
Would you mind adding the method to the interface?

**Comment by dereuromark** [comment]
No problem.

**Comment by ADmad** [comment]
Can we have the method name be shorter "setTimeFromString"?

**Comment by dereuromark** [comment]
Sounds good to me, but bear in mind that this would make Carbon transition non BC then for anyone "upgrading" to ours later... So for API consistency we should not do that at this point as we don't do for other useful changes.

**Comment by lorenzo** [comment]
:+1:

**Comment by dereuromark** [comment]
Squashed.

**Pull request merged**
